backend:
  name: github
  repo: Sandipan04/alumni-website # CHANGE THIS
  branch: main

media_folder: "uploads" # Where photos get saved
public_folder: "/uploads"

collections:
  - name: "alumni"
    label: "Alumni Batches"
    files:
      - name: "all_alumni"
        label: "Manage Alumni List"
        file: "_data/alumni.yml" # Edits this file directly
        fields:
          - {label: "Batch Name (e.g., Int. MSc. 2017-22)", name: "batch", widget: "string"}
          - label: "Students"
            name: "students"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image", required: false}
              - {label: "NISER Supervisor", name: "supervisor", widget: "string"}
              - {label: "Current Position", name: "position", widget: "string"}
              - {label: "Current Institute", name: "institute", widget: "string"}
              - {label: "Email", name: "email", widget: "string", required: false}
              - {label: "Webpage Link", name: "webpage", widget: "string", required: false}
              - {label: "Remarks", name: "remarks", widget: "text", required: false}
